version: 2

jobs:
  core:
    docker:
      - image: rust:1

    steps:
      - checkout

      - restore_cache:
          key: target-cache

      - run: rustc --version; cargo --version; rustup --version
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: cargo fmt -- --check
      - run: cargo test
      - run: cargo clippy
      - run: cargo bench

      - save_cache:
          key: target-cache
          paths:
            - ~/.cargo
            - ./target
  ios:
    macos:
      xcode: "10.0.0"

    steps:
      - checkout
      - run: cd bindings/swift && xcodebuild test -workspace Example/StretchKit.xcworkspace -scheme StretchKit -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.0'


workflows:
  version: 2
  test_all:
    jobs:
      - core
      - ios
