[package]
name = "android-stretch"
version = "0.3.2"
authors = ["Emil SjÃ¶lander <emil@visly.app>"]
edition = "2018"

[dependencies]
jni = { version = "0.10.2", default-features = false }
stretch = "0.3.2"

[lib]
name = "stretch"
crate-type = ["cdylib"]

[workspace]
members = []
